/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@interface SKUIOfferView : NSObject

@property (nonatomic) unsigned long long alignment;
@property (getter=isCompactModeEnabled, nonatomic) bool compactModeEnabled;
@property (readonly, copy) NSString *debugDescription;

@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;

@property (nonatomic) long long metadataPosition;

@property (nonatomic, readonly) NSString *offerViewStateDescription;
@property (getter=isShowingConfirmation, nonatomic) bool showingConfirmation;
@property (readonly) Class superclass;


- (void)_buttonAction:(id)arg1;
- (void)_cancelConfirmationAction:(id)arg1;
- (void)_sendWillAnimate;
- (bool)_shouldHideNoticesWithBuyButtonDescriptor:(id)arg1 context:(id)arg2;
- (void)_showConfirmationAction:(id)arg1;
- (unsigned long long)alignment;
- (id)buttonElements;
- (id)buyButtonDescriptorToButton;
- (id)delegate;
- (id)hlsID;
- (id)hlsPlayButton;
- (bool)isCompactModeEnabled;
- (bool)isShowingConfirmation;
- (void)itemOfferButtonDidAnimateTransition:(id)arg1;
- (void)itemOfferButtonWillAnimateTransition:(id)arg1;
- (void)layoutSubviews;
- (long long)metadataPosition;
- (id)metadataViews;
- (id)notices;
- (id)offerButtonViews;
- (id)offerViewStateDescription;
- (void)reloadWithViewElement:(id)arg1 width:(double)arg2 context:(id)arg3;
- (void)setAlignment:(unsigned long long)arg1;
- (void)setButtonElements:(id)arg1;
- (void)setBuyButtonDescriptorToButton:(id)arg1;
- (void)setCompactModeEnabled:(bool)arg1;

- (void)setDelegate:(id)arg1;
- (void)setHlsID:(id)arg1;
- (void)setHlsPlayButton:(id)arg1;
- (bool)setImage:(id)arg1 forArtworkRequest:(id)arg2 context:(id)arg3;
- (void)setMetadataPosition:(long long)arg1;
- (void)setMetadataViews:(id)arg1;
- (void)setNotices:(id)arg1;
- (void)setOfferButtonViews:(id)arg1;
- (void)setShowingConfirmation:(bool)arg1;

- (bool)updateWithItemState:(id)arg1 context:(id)arg2 animated:(bool)arg3;
- (id)viewForElementIdentifier:(id)arg1;

@end
